package admin.Account.Counselor;// Generated by Selenium IDE
import admin.BaseTest;
import admin.Pages.CounselorManagePage;
import admin.Pages.HomePage;
import admin.Pages.LoginPage;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PSYAdminAccountCounselorModifyTC extends BaseTest {
    LoginPage loginPage = new LoginPage();
    CounselorManagePage counselorManagePage = new CounselorManagePage();

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC01() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();
        String originUserName = counselorManagePage.getUserName();
        counselorManagePage.enterUserName("abcd")
                .enterUserPassword("123abc_")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage//.assertMsgText("修改成功！")
                .clickModifyCounselor();
        String newUserName = counselorManagePage.getUserName();
        counselorManagePage.assertOriginUserName(newUserName,originUserName)
                .closePage();

    }

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC02() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterName("")
                .enterPhone("")
                .enterID("")
                .enterMail("")
                .deleteSup()
                .enterDepartment("")
                .enterCounTitle("")
                .enterUserName("")
                .enterUserPassword("")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertNameErr("请输入姓名")
                .assertPhoneErr("请输入联系电话")
                .assertIDErr("请输入身份证号")
                .assertMailErr("请输入邮箱")
                .assertSupErr("请选择要绑定的督导")
                .assertDepErr("请输入所在部门")
                .assertCounTitleErr("请输入职称")
                .assertUserNameErr("请输入用户名")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC03() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterName("")
                .enterPhone("12345678901")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertNameErr("请输入姓名")
                .assertPhoneErr("格式不正确")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC04() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterName("一")
                .enterPhone("18120149879")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertNameErr("请检查姓名输入是否正确")
                .assertPhoneErr("格式不正确")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC05() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterName("一二三四五六七八九十一二三四五六")
                .enterPhone("1881771234")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertNameErr("请检查姓名输入是否正确")
                .assertPhoneErr("格式不正确")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC06() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterName("张zhang")
                .enterID("212120199876532222")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertNameErr("请检查姓名输入是否正确")
                .assertIDErr("请检查格式后正确输入")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC07() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterName("张#123")
                .enterID("2110032000071543")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertNameErr("请检查姓名输入是否正确")
                .assertIDErr("请检查格式后正确输入")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC08() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterID("2110032001071643211")
                .enterMail("1337140734@com")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertIDErr("请检查格式后正确输入")
                .assertMailErr("请输入合法邮箱")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC09() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterUserPassword("abc12")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertPasswordErr("密码只能由长度为6-20的数字、字母、下划线组成")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC10() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterUserPassword("123456789012345abcde_")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertPasswordErr("密码只能由长度为6-20的数字、字母、下划线组成")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC11() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterUserPassword("123#abc")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertPasswordErr("密码只能由长度为6-20的数字、字母、下划线组成")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyFalseTC12() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterID("21100320010714432x")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertMsgText("修改成功！")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyTrueTC01() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterName("咨询师宝哥")
                .enterPhone("13610002888")
                .enterID("11010119900307053X")
                .enterMail("baoge@126.com")
                .enterDepartment("ECNU食堂")
                .enterCounTitle("超高校级咨询师")
                .enterUserPassword("123ab_")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertMsgText("修改成功！")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyTrueTC02() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterName("咨一")
                .enterUserPassword("123ab_")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertMsgText("修改成功！")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyTrueTC03() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterName("AmyZiXun")
                .enterUserPassword("123ab_")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertMsgText("修改成功！")
                .closePage();
    }

    @Test
    public void pSYAdminAccountConsultantModifyTrueTC04() throws InterruptedException {
        loginPage.login();
        Thread.sleep(2000);
        counselorManagePage.getCounselorManagePage();
        Thread.sleep(1000);
        counselorManagePage.clickModifyCounselor();

        counselorManagePage.enterName("一二三四五六七八九十一二三四五")
                .enterUserPassword("123456789012345abcd_")
                .clickModifyConfirm();
        Thread.sleep(500);
        counselorManagePage.assertMsgText("修改成功！")
                .closePage();
    }


}
