package admin.Login;// Generated by Selenium IDE
import admin.BaseTest;
import admin.Pages.LoginPage;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PSYAdminLoginTC extends BaseTest {
  LoginPage loginPage = new LoginPage();

  @Test //正确执行
  public void pSYAdminLoginTrueTC01() throws InterruptedException {
    loginPage.goLoginPage()
            .enterAccount("ecnu_admin")
            .enterPassword("pl,okm123")
            .clickLogin();
    Thread.sleep(2000);
    loginPage.assertMsgText("登录成功")
            .assertTitle("首页")
            .closePage();
  }

  @Test //未输入账号
  public void pSYAdminLoginFalseTC01() throws InterruptedException {
    loginPage.goLoginPage()
            .enterPassword("pl,okm123")
            .clickLogin();
    Thread.sleep(2000);
    loginPage.assertNoEnter("请输入用户名")
            .closePage();
  }

  @Test //输入错误账号
  public void pSYAdminLoginFalseTC02() throws InterruptedException {
    loginPage.goLoginPage()
            .enterAccount("test")
            .enterPassword("pl,okm123")
            .clickLogin();
    Thread.sleep(2000);
    loginPage.assertMsgText("该用户名不存在或已被禁用，请核实后再登录!")
            .closePage();
  }

  @Test //输入禁用账号
  public void pSYAdminLoginFalseTC03() throws InterruptedException {
    loginPage.goLoginPage()
            .enterAccount("jinyong")
            .enterPassword("pl,okm123")
            .clickLogin();
    Thread.sleep(2000);
    loginPage.assertMsgText("该用户名不存在或已被禁用，请核实后再登录!")
            .closePage();
  }

  @Test //输入禁用账号未输入密码
  public void pSYAdminLoginFalseTC04() throws InterruptedException {
    loginPage.goLoginPage()
            .enterAccount("jinyong")
            .clickLogin();
    loginPage.assertNoEnter("请输入密码")
            .closePage();
  }

  @Test //输入禁用账号输入错误密码
  public void pSYAdminLoginFalseTC05() throws InterruptedException {
    loginPage.goLoginPage()
            .enterAccount("jinyong")
            .enterPassword("kp,okm123")
            .clickLogin();
    Thread.sleep(2000);
    loginPage.assertMsgText("用户名或密码错误!") //not "该用户名不存在或已被禁用，请核实后再登录!"
            .closePage();
  }

  @Test //输入正确账号输入错误密码
  public void pSYAdminLoginFalseTC06() throws InterruptedException {
    loginPage.goLoginPage()
            .enterAccount("ecnu_admin")
            .enterPassword("kp,okm123")
            .clickLogin();
    Thread.sleep(2000);
    loginPage.assertMsgText("用户名或密码错误!")
            .closePage();
  }

}
